import { DAY, HOUR } from '@helpers/time';
import { Task, TaskMode } from '@src';
import { DelayData } from './input/types';

// This file represents configuration settings used by the contract after its deployment.
// The original deployment input settings must be kept intact to be able to verify the deployments.
//
// Delays cannot be set at deployment time: `setDelay` can only be called by the TimelockExecutionHelper, so root has
// to call `scheduleDelayChange` and then `execute` it once `MINIMUM_CHANGE_DELAY_EXECUTION_DELAY` (5 days) has
// elapsed. These arrays therefore describe the delays root is expected to schedule, and are what
// `build-timelock-authorizer-config` and `verify-timelock-authorizer-config` read.
//
// Action IDs come from `action-ids/robinhoodchain/action-ids.json`, generated by
// `npx hardhat save-action-ids --network robinhoodchain`.
//
// NO DELAYS ARE CURRENTLY CONFIGURED: the active `GrantDelays` and `ExecuteDelays` below are empty, so every action
// is executed directly by whoever holds the permission, and permissions are granted immediately. The tiered set that
// would normally be applied is kept below as `ProposedGrantDelays` / `ProposedExecuteDelays`; to turn the timelock
// on, export those as the active arrays instead and follow the scheduling steps in the readme.

const network = 'robinhoodchain';

const Vault = new Task('20260730-v3-vault3', TaskMode.READ_ONLY, network);
const ProtocolFeeController = new Task('20260730-v3-protocol-fee-controller', TaskMode.READ_ONLY, network);
const BushContractRegistry = new Task('20260802-v3-contract-registry', TaskMode.READ_ONLY, network);
const ProtocolFeeSweeper = new Task('20260827-v3-protocol-fee-sweeper-v2', TaskMode.READ_ONLY, network);

// Happens frequently.
const SHORT_DELAY = 0.5 * HOUR;

// May happen frequently but can be dangerous.
const MEDIUM_DELAY = 3 * HOUR;

// Happens basically never. A long delay typically involves replacing infrastructure. This matches the
// `RootTransferDelay` used at deployment.
const LONG_DELAY = DAY;

export const ProposedGrantDelays: DelayData[] = [
  // Fee controller permissions do not affect user funds and are rather infrequent, but do affect collected fees.
  {
    actionId: ProtocolFeeController.actionId('ProtocolFeeController', 'withdrawProtocolFees(address,address)'),
    newDelay: MEDIUM_DELAY,
  },
  {
    actionId: ProtocolFeeController.actionId(
      'ProtocolFeeController',
      'withdrawProtocolFeesForToken(address,address,address)'
    ),
    newDelay: MEDIUM_DELAY,
  },
];

export const ProposedExecuteDelays: DelayData[] = [
  // setAuthorizer must be long since no delay can be longer than it.
  { actionId: Vault.actionId('VaultAdmin', 'setAuthorizer(address)'), newDelay: LONG_DELAY },
  // Queries can be disabled without making it permanent; we must be sure about this.
  { actionId: Vault.actionId('VaultAdmin', 'disableQueryPermanently()'), newDelay: LONG_DELAY },
  // If queries were disabled it was probably for a good reason; it might be dangerous to re-enable.
  { actionId: Vault.actionId('VaultAdmin', 'enableQuery()'), newDelay: MEDIUM_DELAY },
  // Disabling recovery mode is low impact.
  { actionId: Vault.actionId('VaultAdmin', 'disableRecoveryMode(address)'), newDelay: SHORT_DELAY },
  // The fee controller might need replacement, although other than fees it's not dangerous in terms of user funds.
  { actionId: Vault.actionId('VaultAdmin', 'setProtocolFeeController(address)'), newDelay: MEDIUM_DELAY },
  // This is operational, but whoever can call this can set the swap fee percentage for any pool, so it must be checked.
  { actionId: Vault.actionId('VaultAdmin', 'setStaticSwapFeePercentage(address,uint256)'), newDelay: MEDIUM_DELAY },
  // Unpausing a pool is probably dangerous, and is rarely done anyway.
  { actionId: Vault.actionId('VaultAdmin', 'unpausePool(address)'), newDelay: MEDIUM_DELAY },
  // Same for the Vault.
  { actionId: Vault.actionId('VaultAdmin', 'unpauseVault()'), newDelay: MEDIUM_DELAY },
  // And same for the buffers.
  { actionId: Vault.actionId('VaultAdmin', 'unpauseVaultBuffers()'), newDelay: MEDIUM_DELAY },

  // Changing protocol fee percentages for a pool or in general is low impact, operational but rarely done.
  {
    actionId: ProtocolFeeController.actionId('ProtocolFeeController', 'setGlobalProtocolSwapFeePercentage(uint256)'),
    newDelay: SHORT_DELAY,
  },
  {
    actionId: ProtocolFeeController.actionId('ProtocolFeeController', 'setGlobalProtocolYieldFeePercentage(uint256)'),
    newDelay: SHORT_DELAY,
  },
  {
    actionId: ProtocolFeeController.actionId('ProtocolFeeController', 'setProtocolSwapFeePercentage(address,uint256)'),
    newDelay: SHORT_DELAY,
  },
  {
    actionId: ProtocolFeeController.actionId('ProtocolFeeController', 'setProtocolYieldFeePercentage(address,uint256)'),
    newDelay: SHORT_DELAY,
  },

  // The contract registry has mild impact when it comes to trusted routers.
  {
    actionId: BushContractRegistry.actionId('BushContractRegistry', 'addOrUpdateBushContractAlias(string,address)'),
    newDelay: SHORT_DELAY,
  },
  {
    actionId: BushContractRegistry.actionId('BushContractRegistry', 'deprecateBushContract(address)'),
    newDelay: SHORT_DELAY,
  },
  {
    actionId: BushContractRegistry.actionId('BushContractRegistry', 'deregisterBushContract(string)'),
    newDelay: SHORT_DELAY,
  },
  {
    actionId: BushContractRegistry.actionId('BushContractRegistry', 'registerBushContract(uint8,string,address)'),
    newDelay: SHORT_DELAY,
  },

  // Protocol fee sweeper changes are operational and might drain fees if done incorrectly, so medium delay.
  {
    actionId: ProtocolFeeSweeper.actionId('ProtocolFeeSweeper', 'addProtocolFeeBurner(address)'),
    newDelay: MEDIUM_DELAY,
  },
  {
    actionId: ProtocolFeeSweeper.actionId('ProtocolFeeSweeper', 'setFeeRecipient(address)'),
    newDelay: MEDIUM_DELAY,
  },
  {
    actionId: ProtocolFeeSweeper.actionId('ProtocolFeeSweeper', 'setTargetToken(address)'),
    newDelay: MEDIUM_DELAY,
  },
];

// Active configuration. Empty on purpose: see the note at the top of this file.
const GrantDelays: DelayData[] = [];
const ExecuteDelays: DelayData[] = [];

// Checks; these run over the proposed set, so that it stays valid while it is not yet applied.

const actionIds = [
  ProposedExecuteDelays.map((delayData) => delayData.actionId),
  ProposedGrantDelays.map((delayData) => delayData.actionId),
].flat();

if (new Set(actionIds).size !== actionIds.length) {
  throw new Error('Duplicate action ID found in configuration');
}

const delays = [
  ProposedExecuteDelays.map((delayData) => delayData.newDelay),
  ProposedGrantDelays.map((delayData) => delayData.newDelay),
].flat();

if (delays.some((delay) => delay < SHORT_DELAY || delay > LONG_DELAY)) {
  throw new Error('Delays outside expected bounds');
}

export default {
  robinhoodchain: {
    GrantDelays,
    ExecuteDelays,
  },
};
